### PR TITLE
notch.levelGenerator constructor improvements

### PR DESCRIPTION
**Pull request by lukebiddell**
Added an option to provide the Random (useful repeating level generations).
Updated the range of types from 0..2 inclusive to 0..4 inclusive.

### CODE REVIEW

**Comment by amidos2006** [comment]
Sorry for not merging that pull request but the problem with that request is I don't know what exactly changed because it says the whole file is being replaced which is a little scary to merge.

**Comment by lukebiddell** [comment]
Strange, I'll have a look at why that's the case.

**Comment by lukebiddell** [comment]
@amidos2006 I've pushed a fix :) I think you can re-open the ticket

**Comment by lukebiddell** [comment]
New PR opened here https://github.com/amidos2006/Mario-AI-Framework/pull/16

**Pull request closed without merging**
